apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: finops-postgres
spec:
  serviceName: "finops-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: finops-postgres
  template:
    metadata:
      labels:
        app: finops-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "finops_db"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: finops-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: finops-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: finops-postgres-svc
spec:
  selector:
    app: finops-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
